name: Build
on:
  workflow_dispatch:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: feedbin-web
            context: .
            file: Dockerfile
            build-args: FEEDBIN_REPO=https://github.com/AndreasSko/feedbin.git
            tag: latest

          - name: feedbin-web
            context: .
            file: alpine.Dockerfile
            build-args: FEEDBIN_REPO=https://github.com/AndreasSko/feedbin.git
            tag: alpine
    
          - name: feedbin-extract
            file: Dockerfile
            context: feedbin-extract
            tag: latest

          - name: feedbin-image
            file: Dockerfile
            context: feedbin-image
            tag: latest

          - name: feedbin-refresher
            file: Dockerfile
            context: feedbin-refresher
            tag: latest
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          context: ${{ matrix.image.context }}
          push: true
          build-args: ${{ matrix.image.build-args }}
          tags: andreassko/${{ matrix.image.name }}:${{ matrix.image.tag }}
          file: ${{ matrix.image.context }}/${{ matrix.image.file }}
